### ISSUE TITLE
Segmentation fault when opening a park

### ISSUE THREAD

**Issue by BrainShit** [oli414/StreamIntegrationPlugin#3]
Hello,
I tried to setup this plugin with the currently latest version of OpenRCT2 (0.3.3) and I am getting a Segmentation fault when trying to open a park.

```
[StreamIntegration] Loaded
[StreamIntegration] Started
'[StreamIntegration] Connecting...'
VERBOSE: WSAStartup()
Segmentation fault
```
Is what the openrct2 logs say and the Integration Server logs saying
```
Loading config: config_ffa.json
Validating token...
TCP server for communication with OpenRCT2 plugin has been started
Twitch authentication token has been validated
Completed Twitch authentication
Connected to PubSub
Connected to Twitch chat
All systems are up and running. Waiting for OpenRCT2 plugin to connect...
TCP connection with OpenRCT2 plugin has been established
All systems are up and running. Ready to stream!
Error in TCP connection: Error: read ECONNRESET
```

and I'm not 100% sure where the issue lies.
I tried changing the port on which the server is running and the plugin is talking to (from 8081 to 8089) just to be sure that it's not another service on my pc trying to interfere but that didn't change anything.

I'm using all the default configuration you provided.

I hope you can help me!

**Comment by oli414** [comment]
I'm getting a crash on the latest release version as well.

Most people play on the develop version so my plugins generally aim to work for that. 

If you wish to play on release you can download an older version of the plugin and try that, but it'll either not have the peep names working, or have a significant impact on performance. I'm guessing that the feature that was added that allowed me to fix that bug has not made its way to a stable release version yet.

**Comment by oli414** [comment]
I've updated the readme to reflect this as well, let me know if you're still having trouble!
