### ISSUE TITLE
Certain commands not working?

### ISSUE THREAD

**Issue by TheLostMeme** [oli414/StreamIntegrationPlugin#4]
Openrct2 version: 0.4.4 d6ebeca (dev branch)

I just did a quick test on my machine and it seems like every command that isn't a coloring command does not work (example being !donate and !steal bring up a "Unknown custom action" red box in-game).

Video of the error in action here: https://streamable.com/t178h1

Is there a fix for this? Really wanted to get this up and running for my stream today.

**Comment by tarakaminarito** [comment]
went through the same issue.

fixed it by using OpenRCT2 0.3.4!

it might work with later versions, but i know that it will work with that version!

**Comment by TheLostMeme** [comment]
thank you, will use 0.3.4 from now on for the plugin!
